#!/usr/bin/env python3
"""Her deponun README banner'ini banners.json'dan uretir (SVG, 1280x320).

Tek sablon, tek veri dosyasi: 27 depo ayni ailede gorunur, ama her biri
kendi alan rengini ve kendi dogrulanmis olgularini tasir. Banner'da hic
sayac yok (test sayisi, surum): sayilar degisir, bir gorsel degismez ve
eskiyen bir sayi tam da bu hesabin temizledigi hataydi.

    python3 assets/banner/banner.py            # hepsini assets/banner/out/ altina yaz
    python3 assets/banner/banner.py mcp-vet    # yalnizca biri
    python3 assets/banner/banner.py --kontrol  # uzunluk/alan kurallarini denetle

SVG saf metin ve vektor: yazi tipi olarak sistemin monospace/sans
ailesini kullanir, disaridan hicbir sey yuklemez.
"""

import html
import re
import json
import sys
from pathlib import Path

KOK = Path(__file__).resolve().parent
RENK = {  # alan -> vurgu; sosyal kartlar ve profildeki alanlarla ayni
    "denetim": "#58a6ff",
    "altyapi": "#e3b341",
    "mcp": "#3fb950",
    "uygulama": "#39c5cf",
    "oyun": "#db61a2",
}
ALAN_ADI = {
    "denetim": "TOOLS THAT CHECK",
    "altyapi": "AGENT INFRASTRUCTURE",
    "mcp": "MCP SERVER",
    "uygulama": "APP",
    "oyun": "GAME",
}
MONO = "ui-monospace,SFMono-Regular,'SF Mono',Menlo,Consolas,'DejaVu Sans Mono',monospace"
SANS = "-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,'DejaVu Sans',sans-serif"
SINIR = {"ad": 26, "satir": 58, "cip": 26, "etiket": 8, "deger": 34}


def e(s):
    return html.escape(s, quote=True)


def svg(ad, b):
    v = RENK[b["alan"]]
    ust = b.get("ust") or ALAN_ADI[b["alan"]]
    boy = 60 if len(ad) <= 18 else 48
    # uzun adlar her yazi tipinde ayirici cizginin soluna sigsin diye sikistirilir
    uzun = f' textLength="{min(len(ad) * 29, 680)}" lengthAdjust="spacingAndGlyphs"' if boy == 48 else ""
    satirlar = "".join(
        f'<text x="72" y="{176 + i * 30}" class="p">{e(s)}</text>'
        for i, s in enumerate(b["satirlar"]))
    x, cipler = 72, []
    for c in b["cipler"]:
        w = 20 + len(c) * 8.4
        cipler.append(f'<rect x="{x}" y="244" width="{w:.0f}" height="30" rx="15" class="c"/>'
                      f'<text x="{x + w / 2:.0f}" y="264" class="ct" text-anchor="middle">{e(c)}</text>')
        x += w + 10
    olgular = "".join(
        f'<circle cx="826" cy="{96 + i * 38}" r="4" fill="{v}" opacity="{1 - i * 0.15:.2f}"/>'
        f'<text x="842" y="{101 + i * 38}" class="k">{e(k)}</text>'
        f'<text x="930" y="{101 + i * 38}" class="d">{e(d)}</text>'
        for i, (k, d) in enumerate(b["olgular"]))
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="320" viewBox="0 0 1280 320" role="img" aria-labelledby="t d">
<!-- generated by github.com/Furkiozknn/Furkiozknn assets/banner/banner.py; edit banners.json there, not this file -->
<title id="t">{e(ad)}</title><desc id="d">{e(" ".join(b["satirlar"]))}</desc>
<defs><radialGradient id="g" cx="1" cy="0" r="0.9"><stop offset="0" stop-color="{v}" stop-opacity=".16"/><stop offset="1" stop-color="{v}" stop-opacity="0"/></radialGradient>
<style>.u{{font:700 13px/1 {SANS};letter-spacing:.22em;fill:#d4a95c}}.n{{font:700 {boy}px/1 {MONO};fill:#f2efe6}}
.p{{font:400 21px/1 {SANS};fill:#c9d1d9}}.c{{fill:none;stroke:{v};stroke-opacity:.55}}.ct{{font:600 13px/1 {MONO};fill:{v}}}
.k{{font:400 13px/1 {MONO};fill:#7d8590}}.d{{font:500 14px/1 {MONO};fill:#e6edf3}}.f{{font:400 12px/1 {MONO};fill:#484f58}}</style></defs>
<rect width="1280" height="320" rx="14" fill="#0d1117"/><rect width="1280" height="320" rx="14" fill="url(#g)"/>
<rect x="0.5" y="0.5" width="1279" height="319" rx="13.5" fill="none" stroke="#30363d"/>
<rect x="72" y="0" width="140" height="4" fill="{v}"/>
<text x="72" y="64" class="u">{e(ust)}</text>
<text x="72" y="{128 if boy == 60 else 124}" class="n"{uzun}>{e(ad)}</text>
{satirlar}{"".join(cipler)}
<line x1="790" y1="60" x2="790" y2="260" stroke="#30363d"/>
{olgular}
<text x="1208" y="290" class="f" text-anchor="end">github.com/Furkiozknn/{e(ad)}</text>
</svg>
'''


def kontrol(veri):
    hata = []
    for ad, b in veri.items():
        if b["alan"] not in RENK:
            hata.append(f"{ad}: bilinmeyen alan {b['alan']}")
        if len(ad) > SINIR["ad"]:
            hata.append(f"{ad}: ad cok uzun")
        if not 1 <= len(b["satirlar"]) <= 2 or any(len(s) > SINIR["satir"] for s in b["satirlar"]):
            hata.append(f"{ad}: satirlar 1-2 adet, en fazla {SINIR['satir']} karakter")
        if len(b["cipler"]) > 3 or any(len(c) > SINIR["cip"] for c in b["cipler"]):
            hata.append(f"{ad}: en fazla 3 cip, her biri {SINIR['cip']} karakter")
        if sum(20 + len(c) * 8.4 + 10 for c in b["cipler"]) > 700:
            hata.append(f"{ad}: cipler sol alana sigmiyor")
        if len(b["olgular"]) != 5:
            hata.append(f"{ad}: tam 5 olgu satiri")
        for k, d in b["olgular"]:
            if len(k) > SINIR["etiket"] or len(d) > SINIR["deger"]:
                hata.append(f"{ad}: olgu cok uzun: {k} / {d}")
        metin = " ".join(b["satirlar"] + b["cipler"] + [d for _, d in b["olgular"]])
        if re.search(r"\d[\d,.]*\s*(tests?|test|passed)\b", metin.lower()):
            hata.append(f"{ad}: banner'da test sayisi olmaz")
    return hata


def main(arg):
    veri = json.loads((KOK / "banners.json").read_text(encoding="utf-8"))
    if arg[:1] == ["--kontrol"]:
        hata = kontrol(veri)
        print("\n".join(hata) or "banners.json kurallara uyuyor (%d depo)." % len(veri))
        return 1 if hata else 0
    hata = kontrol(veri)
    if hata:
        print("\n".join(hata))
        return 1
    cikti = KOK / "out"
    cikti.mkdir(exist_ok=True)
    for ad in arg or sorted(veri):
        (cikti / f"{ad}.svg").write_text(svg(ad, veri[ad]), encoding="utf-8")
        print("yaz  out/%s.svg" % ad)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
